package com.mcgo.app.ui.screens

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExposedDropdownMenuAnchorType
import androidx.compose.material3.ExposedDropdownMenuBox
import androidx.compose.material3.ExposedDropdownMenuDefaults
import androidx.compose.material3.FilterChip
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.mcgo.app.server.resolveProvisionablePaperVersionOptions
import com.mcgo.app.ui.model.JavaSelectionMode
import com.mcgo.app.ui.model.MinecraftServerType
import com.mcgo.app.ui.model.ServerCardState
import com.mcgo.app.ui.model.createFabricServer
import com.mcgo.app.ui.model.createForgeServer
import com.mcgo.app.ui.model.createNeoForgeServer
import com.mcgo.app.ui.model.createPaperServer
import com.mcgo.app.ui.model.createPurpurServer
import com.mcgo.app.ui.model.createQuiltServer
import com.mcgo.app.ui.model.createVanillaServer
import com.mcgo.app.ui.model.pickAvailableManagedServerPort
import com.mcgo.app.ui.model.recommendedJavaMajorVersion

@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun CreateServerDialog(
    servers: List<ServerCardState>,
    vanillaVersions: List<String>,
    paperVersions: List<String>,
    purpurVersions: List<String>,
    fabricVersions: List<String>,
    forgeVersions: List<String>,
    neoForgeVersions: List<String>,
    quiltVersions: List<String>,
    supportedProvisionableJavaVersions: Set<Int>,
    onDismiss: () -> Unit,
    onCreate: (ServerCardState) -> Unit,
    onCreateFromModpack: (ServerCardState, android.net.Uri) -> Unit,
    onOpenModpackPicker: (ServerCardState) -> Unit,
    onCancelModpackPicker: (ServerCardState) -> Unit,
) {
    val vanillaVersionOptions = remember(vanillaVersions, supportedProvisionableJavaVersions) {
        vanillaVersions.filter { recommendedJavaMajorVersion(it) in supportedProvisionableJavaVersions }
    }
    val paperVersionOptions = remember(paperVersions, supportedProvisionableJavaVersions) {
        resolveProvisionablePaperVersionOptions(paperVersions, supportedProvisionableJavaVersions)
    }
    val purpurVersionOptions = remember(purpurVersions, supportedProvisionableJavaVersions) {
        purpurVersions.filter { recommendedJavaMajorVersion(it) in supportedProvisionableJavaVersions }
    }
    val fabricVersionOptions = remember(fabricVersions, supportedProvisionableJavaVersions) {
        fabricVersions.filter { recommendedJavaMajorVersion(it) in supportedProvisionableJavaVersions }
    }
    val forgeVersionOptions = remember(forgeVersions, supportedProvisionableJavaVersions) {
        forgeVersions.filter { recommendedJavaMajorVersion(it) in supportedProvisionableJavaVersions }
    }
    val neoForgeVersionOptions = remember(neoForgeVersions, supportedProvisionableJavaVersions) {
        neoForgeVersions.filter { recommendedJavaMajorVersion(it) in supportedProvisionableJavaVersions }
    }
    val quiltVersionOptions = remember(quiltVersions, supportedProvisionableJavaVersions) {
        quiltVersions.filter { recommendedJavaMajorVersion(it) in supportedProvisionableJavaVersions }
    }
    var selectedServerType by remember { mutableStateOf(MinecraftServerType.Paper) }
    var name by remember { mutableStateOf("Paper 服务器") }
    var lastAutoGeneratedName by remember { mutableStateOf("Paper 服务器") }
    var minecraftVersion by remember { mutableStateOf("") }
    var versionWasAutoSelected by remember { mutableStateOf(true) }
    var versionMenuExpanded by remember { mutableStateOf(false) }
    var javaSelectionMode by remember { mutableStateOf(JavaSelectionMode.Recommended) }
    var javaVersionMenuExpanded by remember { mutableStateOf(false) }
    var selectedJavaMajorVersion by remember { mutableStateOf(recommendedJavaMajorVersion(minecraftVersion)) }
    var maxPlayers by remember { mutableStateOf("20") }
    var memoryMb by remember { mutableStateOf("2048") }
    val resolvedMaxPlayers = maxPlayers.toIntOrNull()?.coerceIn(1, 200) ?: 20
    val resolvedMemoryMb = memoryMb.toIntOrNull()?.coerceAtLeast(512) ?: 2048
    val resolvedPort = remember(servers) { pickAvailableManagedServerPort(servers) }
    val recommendedJava = remember(minecraftVersion) { recommendedJavaMajorVersion(minecraftVersion) }
    val previewServerId = remember { "draft-server-preview-${System.currentTimeMillis()}" }
    val importName = if (name.isBlank() || name == lastAutoGeneratedName) "整合包服务器" else name
    val modpackPreviewServer = createFabricServer(
        name = importName,
        minecraftVersion = "1.21.4",
        maxPlayers = resolvedMaxPlayers,
        memoryMb = resolvedMemoryMb,
        port = resolvedPort,
        javaMajorVersion = 21,
        javaSelectionMode = JavaSelectionMode.Recommended,
    ).copy(
        id = previewServerId,
        edition = "整合包 导入后自动识别",
    )
    val modpackImportLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenDocument(),
    ) { uri ->
        if (uri == null) {
            onCancelModpackPicker(modpackPreviewServer.copy(name = importName))
        } else {
            onCreateFromModpack(modpackPreviewServer.copy(name = importName), uri)
            onDismiss()
        }
    }
    val javaVersionOptions = remember(
        supportedProvisionableJavaVersions,
        selectedJavaMajorVersion,
        recommendedJava,
    ) {
        buildList {
            add(recommendedJava)
            add(selectedJavaMajorVersion)
            addAll(supportedProvisionableJavaVersions)
        }.distinct().sorted()
    }
    LaunchedEffect(minecraftVersion, javaSelectionMode) {
        if (javaSelectionMode == JavaSelectionMode.Recommended) {
            selectedJavaMajorVersion = recommendedJava
        }
    }
    LaunchedEffect(selectedServerType) {
        val defaultName = when (selectedServerType) {
            MinecraftServerType.Vanilla -> "Vanilla 服务器"
            MinecraftServerType.Paper -> "Paper 服务器"
            MinecraftServerType.Purpur -> "Purpur 服务器"
            MinecraftServerType.Fabric -> "Fabric 服务器"
            MinecraftServerType.Forge -> "Forge 服务器"
            MinecraftServerType.NeoForge -> "NeoForge 服务器"
            MinecraftServerType.Quilt -> "Quilt 服务器"
        }
        if (name.isBlank() || name == lastAutoGeneratedName) {
            name = defaultName
        }
        lastAutoGeneratedName = defaultName
    }
    LaunchedEffect(selectedServerType, vanillaVersionOptions, paperVersionOptions, purpurVersionOptions, fabricVersionOptions, forgeVersionOptions, neoForgeVersionOptions, quiltVersionOptions) {
        val versionOptions = when (selectedServerType) {
            MinecraftServerType.Vanilla -> vanillaVersionOptions
            MinecraftServerType.Paper -> paperVersionOptions
            MinecraftServerType.Purpur -> purpurVersionOptions
            MinecraftServerType.Fabric -> fabricVersionOptions
            MinecraftServerType.Forge -> forgeVersionOptions
            MinecraftServerType.NeoForge -> neoForgeVersionOptions
            MinecraftServerType.Quilt -> quiltVersionOptions
        }
        if (minecraftVersion !in versionOptions || versionWasAutoSelected) {
            minecraftVersion = versionOptions.lastOrNull().orEmpty()
            versionWasAutoSelected = true
        }
    }
    val previewMinecraftVersion = when (selectedServerType) {
        MinecraftServerType.Vanilla -> minecraftVersion.ifBlank { vanillaVersionOptions.lastOrNull().orEmpty() }
        MinecraftServerType.Paper -> minecraftVersion.ifBlank { paperVersionOptions.lastOrNull().orEmpty() }
        MinecraftServerType.Purpur -> minecraftVersion.ifBlank { purpurVersionOptions.lastOrNull().orEmpty() }
        MinecraftServerType.Fabric -> minecraftVersion.ifBlank { fabricVersionOptions.lastOrNull().orEmpty() }
        MinecraftServerType.Forge -> minecraftVersion.ifBlank { forgeVersionOptions.lastOrNull().orEmpty() }
        MinecraftServerType.NeoForge -> minecraftVersion.ifBlank { neoForgeVersionOptions.lastOrNull().orEmpty() }
        MinecraftServerType.Quilt -> minecraftVersion.ifBlank { quiltVersionOptions.lastOrNull().orEmpty() }
    }
    val previewServer = createServerFromDialogSelection(
        selectedServerType = selectedServerType,
        name = name,
        minecraftVersion = previewMinecraftVersion,
        maxPlayers = resolvedMaxPlayers,
        memoryMb = resolvedMemoryMb,
        port = resolvedPort,
        javaMajorVersion = selectedJavaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    ).copy(id = previewServerId)
    val canCreate = name.isNotBlank() && minecraftVersion.isNotBlank()

    AlertDialog(
        onDismissRequest = {},
        confirmButton = {
            TextButton(
                enabled = canCreate,
                onClick = {
                    val server = createServerFromDialogSelection(
                        selectedServerType = selectedServerType,
                        name = name,
                        minecraftVersion = minecraftVersion,
                        maxPlayers = resolvedMaxPlayers,
                        memoryMb = resolvedMemoryMb,
                        port = resolvedPort,
                        javaMajorVersion = selectedJavaMajorVersion,
                        javaSelectionMode = javaSelectionMode,
                    )
                    onCreate(server)
                    onDismiss()
                },
            ) {
                Text("创建服务器")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("取消") }
        },
        title = { Text("创建服务器") },
        text = {
            CreateServerStandardContent(
                selectedServerType = selectedServerType,
                onSelectServerType = { selectedServerType = it },
                name = name,
                onNameChange = { name = it },
                minecraftVersion = minecraftVersion,
                versionMenuExpanded = versionMenuExpanded,
                onVersionMenuExpandedChange = { versionMenuExpanded = it },
                javaSelectionMode = javaSelectionMode,
                javaVersionMenuExpanded = javaVersionMenuExpanded,
                onJavaVersionMenuExpandedChange = { javaVersionMenuExpanded = it },
                selectedJavaMajorVersion = selectedJavaMajorVersion,
                recommendedJava = recommendedJava,
                javaVersionOptions = javaVersionOptions,
                onAutoJavaSelected = {
                    javaSelectionMode = JavaSelectionMode.Recommended
                    selectedJavaMajorVersion = recommendedJava
                },
                onManualJavaSelected = { version ->
                    javaSelectionMode = JavaSelectionMode.Manual
                    selectedJavaMajorVersion = version
                },
                maxPlayers = maxPlayers,
                memoryMb = memoryMb,
                onMaxPlayersChange = { maxPlayers = it.filter(Char::isDigit) },
                onMemoryMbChange = { memoryMb = it.filter(Char::isDigit) },
                vanillaVersionOptions = vanillaVersionOptions,
                paperVersionOptions = paperVersionOptions,
                purpurVersionOptions = purpurVersionOptions,
                fabricVersionOptions = fabricVersionOptions,
                forgeVersionOptions = forgeVersionOptions,
                neoForgeVersionOptions = neoForgeVersionOptions,
                quiltVersionOptions = quiltVersionOptions,
                onVersionSelected = { version ->
                    minecraftVersion = version
                    versionWasAutoSelected = false
                    versionMenuExpanded = false
                },
                onLaunchModpackPicker = {
                    onOpenModpackPicker(modpackPreviewServer.copy(name = importName))
                    modpackImportLauncher.launch(arrayOf("application/zip", "application/octet-stream", "*/*"))
                },
            )
        },
    )
}


private fun createServerFromDialogSelection(
    selectedServerType: MinecraftServerType,
    name: String,
    minecraftVersion: String,
    maxPlayers: Int,
    memoryMb: Int,
    port: Int,
    javaMajorVersion: Int,
    javaSelectionMode: JavaSelectionMode,
): ServerCardState = when (selectedServerType) {
    MinecraftServerType.Vanilla -> createVanillaServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
    MinecraftServerType.Paper -> createPaperServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
    MinecraftServerType.Purpur -> createPurpurServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
    MinecraftServerType.Fabric -> createFabricServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
    MinecraftServerType.Forge -> createForgeServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
    MinecraftServerType.NeoForge -> createNeoForgeServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
    MinecraftServerType.Quilt -> createQuiltServer(
        name = name,
        minecraftVersion = minecraftVersion,
        maxPlayers = maxPlayers,
        memoryMb = memoryMb,
        port = port,
        javaMajorVersion = javaMajorVersion,
        javaSelectionMode = javaSelectionMode,
    )
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun CreateServerStandardContent(
    selectedServerType: MinecraftServerType,
    onSelectServerType: (MinecraftServerType) -> Unit,
    name: String,
    onNameChange: (String) -> Unit,
    minecraftVersion: String,
    versionMenuExpanded: Boolean,
    onVersionMenuExpandedChange: (Boolean) -> Unit,
    javaSelectionMode: JavaSelectionMode,
    javaVersionMenuExpanded: Boolean,
    onJavaVersionMenuExpandedChange: (Boolean) -> Unit,
    selectedJavaMajorVersion: Int,
    recommendedJava: Int,
    javaVersionOptions: List<Int>,
    onAutoJavaSelected: () -> Unit,
    onManualJavaSelected: (Int) -> Unit,
    maxPlayers: String,
    memoryMb: String,
    onMaxPlayersChange: (String) -> Unit,
    onMemoryMbChange: (String) -> Unit,
    vanillaVersionOptions: List<String>,
    paperVersionOptions: List<String>,
    purpurVersionOptions: List<String>,
    fabricVersionOptions: List<String>,
    forgeVersionOptions: List<String>,
    neoForgeVersionOptions: List<String>,
    quiltVersionOptions: List<String>,
    onVersionSelected: (String) -> Unit,
    onLaunchModpackPicker: () -> Unit,
) {
    Column(
        modifier = Modifier.verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        TextButton(onClick = onLaunchModpackPicker) {
            Text("导入整合包")
        }
        FlowRow(
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            MinecraftServerType.entries.forEach { type ->
                FilterChip(
                    selected = selectedServerType == type,
                    onClick = { onSelectServerType(type) },
                    label = { Text(type.label) },
                )
            }
        }
        OutlinedTextField(
            value = name,
            onValueChange = onNameChange,
            modifier = Modifier.fillMaxWidth(),
            label = { Text("服务器名称") },
            singleLine = true,
        )
        ExposedDropdownMenuBox(
            expanded = versionMenuExpanded,
            onExpandedChange = { onVersionMenuExpandedChange(!versionMenuExpanded) },
            modifier = Modifier.fillMaxWidth(),
        ) {
            val versionOptions = when (selectedServerType) {
                MinecraftServerType.Vanilla -> vanillaVersionOptions
                MinecraftServerType.Paper -> paperVersionOptions
                MinecraftServerType.Purpur -> purpurVersionOptions
                MinecraftServerType.Fabric -> fabricVersionOptions
                MinecraftServerType.Forge -> forgeVersionOptions
                MinecraftServerType.NeoForge -> neoForgeVersionOptions
                MinecraftServerType.Quilt -> quiltVersionOptions
            }
            OutlinedTextField(
                value = minecraftVersion,
                onValueChange = {},
                modifier = Modifier
                    .menuAnchor(ExposedDropdownMenuAnchorType.PrimaryNotEditable, true)
                    .fillMaxWidth(),
                readOnly = true,
                label = { Text("Minecraft 版本") },
                supportingText = {
                    Text(
                        when (selectedServerType) {
                            MinecraftServerType.Vanilla -> "从 Vanilla 官方版本列表选择"
                            MinecraftServerType.Paper -> "从 Paper 官方版本列表选择"
                            MinecraftServerType.Purpur -> "从 Purpur 官方版本列表选择"
                            MinecraftServerType.Fabric -> "从 Fabric 官方版本列表选择"
                            MinecraftServerType.Forge -> "从 Forge 官方版本列表选择"
                            MinecraftServerType.NeoForge -> "从 NeoForge 官方版本列表选择"
                            MinecraftServerType.Quilt -> "从 Quilt 官方版本列表选择"
                        },
                    )
                },
                singleLine = true,
                trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = versionMenuExpanded) },
            )
            ExposedDropdownMenu(
                expanded = versionMenuExpanded,
                onDismissRequest = { onVersionMenuExpandedChange(false) },
            ) {
                versionOptions.asReversed().forEach { version ->
                    DropdownMenuItem(
                        text = { Text(version) },
                        onClick = { onVersionSelected(version) },
                    )
                }
            }
        }
        ExposedDropdownMenuBox(
            expanded = javaVersionMenuExpanded,
            onExpandedChange = { onJavaVersionMenuExpandedChange(!javaVersionMenuExpanded) },
            modifier = Modifier.fillMaxWidth(),
        ) {
            OutlinedTextField(
                value = if (javaSelectionMode == JavaSelectionMode.Recommended) "自动" else "Java $selectedJavaMajorVersion",
                onValueChange = {},
                modifier = Modifier
                    .menuAnchor(ExposedDropdownMenuAnchorType.PrimaryNotEditable, true)
                    .fillMaxWidth(),
                readOnly = true,
                label = { Text("运行时 Java") },
                supportingText = { Text("当前推荐：Java $recommendedJava") },
                singleLine = true,
                trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = javaVersionMenuExpanded) },
            )
            ExposedDropdownMenu(
                expanded = javaVersionMenuExpanded,
                onDismissRequest = { onJavaVersionMenuExpandedChange(false) },
            ) {
                val javaMenuOptions = listOf<String>("自动") + javaVersionOptions.map { "Java $it" }
                javaMenuOptions.forEach { selected ->
                    DropdownMenuItem(
                        text = { Text(selected) },
                        onClick = {
                            if (selected == "自动") onAutoJavaSelected() else onManualJavaSelected(selected.removePrefix("Java ").toIntOrNull() ?: selectedJavaMajorVersion)
                            onJavaVersionMenuExpandedChange(false)
                        },
                    )
                }
            }
        }
        OutlinedTextField(
            value = maxPlayers,
            onValueChange = onMaxPlayersChange,
            modifier = Modifier.fillMaxWidth(),
            label = { Text("最大玩家数") },
            singleLine = true,
        )
        OutlinedTextField(
            value = memoryMb,
            onValueChange = onMemoryMbChange,
            modifier = Modifier.fillMaxWidth(),
            label = { Text("内存 MB") },
            singleLine = true,
        )
    }
}
